export const SAVE_SUSCRIBER = 'SAVE_SUSCRIBER'
export const SAVE_SUSCRIBER_SUCCESS = 'SAVE_SUSCRIBER_SUCCESS'
export const SAVE_SUSCRIBER_FAILURE = 'SAVE_SUSCRIBER_FAILURE'

export const SAVE_CONTACT = 'SAVE_CONTACT'
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS'
export const SAVE_CONTACT_FAILURE = 'SAVE_CONTACT_FAILURE'